name: boards
channels:
  - conda-forge
dependencies:
  - python==3.6
  - django
  - pip:
      - coverage
      - markdown
      - psycopg2-binary
      - whitenoise
      - django_heroku
      - django_user_agents
      - python-memcached
      - markdown
      - dj_database_url
      - python-decouple