# Generated by Django 2.1.5 on 2019-01-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_auto_20190118_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
