# Generated by Django 2.1.5 on 2019-02-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0005_auto_20190201_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
